name: Build Resume PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Because GitHub's Ubuntu runners come with Docker pre-installed,
      # we can literally just trigger your existing Makefile!
      - name: Build all templates
        run: make all

      # Upload any PDF generated in the root directory
      - name: Upload PDF Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kevin_Aimaier_Resumes
          path: '*.pdf'